# Generated by Django 5.0.2 on 2024-04-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_camera',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.IntegerField(null=True),
        ),
    ]
