# Generated by Django 5.0.2 on 2024-04-21 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_product_p_camera_product_ram_product_storage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='p_camera',
            new_name='primary_camera',
        ),
    ]
