# Generated by Django 5.0.2 on 2024-04-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_rename_p_camera_product_primary_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='connectivity',
            field=models.IntegerField(default=4, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(default=200, null=True),
        ),
    ]
