# Generated by Django 5.0.2 on 2024-04-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_product_connectivity_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='connectivity',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='primary_camera',
            field=models.IntegerField(default=48),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage',
            field=models.IntegerField(default=128),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.IntegerField(default=200),
        ),
    ]
